name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Use the version of Go in your project

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v ./...

    - name: Test
      run: go test ./... -v
