name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v ./...

    - name: Test with Coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Use GoCover.io to generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    # Optional: Upload coverage report to a service like Codecov or Coveralls
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
