name: Go with Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18' # Specify your Go version

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test with Coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.out
        flag-name: Go Tests # Optional
        parallel: false # Optional
