name: Go Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Specify your Go version

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test with Coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Generate Coverage Report
      run: go tool cover -func=coverage.out

    # Optional: Upload coverage report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: go-coverage-report
        path: coverage.out
